### ISSUE TITLE
Track 1

### ISSUE THREAD

**Issue by joker5bb** [dimalinux/SwipeYours#3]
Why did you remove track 1 support? It's necessary for most POS systems otherwise it will give card error.

**Comment by dimalinux** [comment]
I didn't remove track 1 support.  The VISA MSD protocol implemented only uses track 2 equivalent data.  I parse the track 1 data, if it is given, for display purposes only.

**Comment by joker5bb** [comment]
which visa protocol uses track 1

**Comment by cjames253** [comment]
Who's this
