### ISSUE TITLE
Reading Transaction Details

### ISSUE THREAD

**Issue by pravinuttarwar** [dimalinux/SwipeYours#4]
Can we read transaction details like amount once nfc payment is done?

**Comment by dimalinux** [comment]
No. The obsolete protocol that this app implemented didn't exchange a payment amount.  The protocol was called "Visa MSD", where MSD stood for "magnetic stripe data".  It just switched the transfer mechanism from card-swiping to card-tapping without making any major change to the actual data being exchanged.

**Comment by charllao** [comment]
My well-known Brazilian colleague made an update through his application, in which he made some changes and now his application works again here in Brazil, would you be able to help us so that we can update it too?

**Comment by charllao** [comment]
![Image](https://i.imgur.com/00s0u0U.jpg)
